[workspace]
members = ["."]
resolver = "2"

[package]
name = "pocketjs-esp32-core"
version = "0.1.1"
edition = "2021"
license = "MIT"
publish = false

[lib]
name = "pocketjs_esp32_core"
crate-type = ["staticlib"]

[dependencies]
pocketjs-core = { path = "../vendor/pocketjs/engine/core" }
pocketjs-esp32p4-ppa = { path = "../vendor/pocketjs/engine/backends/esp32p4-ppa" }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = "debuginfo"
