#pragma once

#include <stddef.h>
#include <stdint.h>

#include "esp_err.h"
#include "pocketjs_display.h"

#ifdef __cplusplus
extern "C" {
#endif

#define POCKETJS_TARGET_ID "esp32p4-idf"
#define POCKETJS_HOST_ABI 1U
#define POCKETJS_HEADLESS_TARGET_ID 2U

typedef struct pocketjs pocketjs_t;
struct pocketjs_extension;

/**
 * Generated by pocketjs_compile_app() or pocketjs_embed_package().
 *
 * package_data must remain readable until pocketjs_destroy() returns.
 */
typedef struct {
    const uint8_t *package_data;
    size_t package_size;
    const char *target_id;
    uint32_t host_abi;
    uint32_t logical_width;
    uint32_t logical_height;
    uint32_t raster_density;
    pocketjs_pixel_format_t pixel_format;
} pocketjs_app_t;

typedef struct {
    size_t javascript_heap_limit;
    size_t javascript_stack_limit;
    const struct pocketjs_extension *extensions;
    size_t extension_count;
} pocketjs_config_t;

#define POCKETJS_DEFAULT_CONFIG()                                      \
    {                                                                  \
        .javascript_heap_limit = 12U * 1024U * 1024U,                  \
        .javascript_stack_limit = 512U * 1024U,                        \
        .extensions = NULL,                                            \
        .extension_count = 0,                                          \
    }

typedef struct {
    uint32_t buttons;
    int16_t analog_x;
    int16_t analog_y;
} pocketjs_input_t;

typedef struct {
    uint32_t javascript_us;
    uint32_t core_tick_us;
    uint32_t render_us;
    uint32_t flush_wait_us;
    uint32_t total_us;
    uint32_t ppa_fills;
    uint32_t ppa_blends;
    uint32_t ppa_srm;
    uint32_t software_ops;
    uint32_t software_words;
    uint32_t damage_regions;
    uint32_t damage_pixels;
    uint32_t full_redraw;
} pocketjs_frame_stats_t;

esp_err_t pocketjs_create(
    const pocketjs_app_t *app,
    const pocketjs_config_t *config,
    pocketjs_t **out_runtime
);

esp_err_t pocketjs_attach_display(
    pocketjs_t *runtime,
    pocketjs_display_t *display
);

esp_err_t pocketjs_detach_display(pocketjs_t *runtime);

esp_err_t pocketjs_run_frame(
    pocketjs_t *runtime,
    const pocketjs_input_t *input,
    pocketjs_frame_stats_t *out_stats
);

void pocketjs_destroy(pocketjs_t *runtime);

#ifdef __cplusplus
}
#endif
